# Generated by Django 3.0.6 on 2020-05-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zcblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categroy',
            new_name='Category',
        ),
    ]
